blank_issues_enabled: false
contact_links:
  - name: Discord chat support
    url: https://discord.gg/YWrKVTn
    about: Realtime support / chat with the community and the team.

  - name: Discourse discussion forum
    url: https://discourse.linuxserver.io
    about: Post on our community forum.

  - name: Documentation
    url: https://docs.linuxserver.io/images/docker-wireguard
    about: Documentation - information about all of our containers.
