name: External Trigger Scheduler

on:
  schedule:
    - cron:  '51 * * * *'
  workflow_dispatch:

jobs:
  external-trigger-scheduler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: '0'

      - name: External Trigger Scheduler
        run: |
          printf "# External trigger scheduler for docker-wireguard\n\n" >> $GITHUB_STEP_SUMMARY
          printf "Found the branches:\n\n%s\n" "$(git for-each-ref --format='- %(refname:lstrip=3)' refs/remotes)" >> $GITHUB_STEP_SUMMARY
          for br in $(git for-each-ref --format='%(refname:lstrip=3)' refs/remotes)
          do
            if [[ "${br}" == "HEAD" ]]; then
              printf "\nSkipping %s.\n" ${br} >> $GITHUB_STEP_SUMMARY
              continue
            fi
            printf "\n## Evaluating \`%s\`\n\n" ${br} >> $GITHUB_STEP_SUMMARY
            ls_jenkins_vars=$(curl -sX GET https://raw.githubusercontent.com/linuxserver/docker-wireguard/${br}/jenkins-vars.yml)
            ls_branch=$(echo "${ls_jenkins_vars}" | yq -r '.ls_branch')
            ls_trigger=$(echo "${ls_jenkins_vars}" | yq -r '.external_type')
            if [[ "${br}" == "${ls_branch}" ]] && [[ "${ls_trigger}" != "os" ]]; then
              echo "Branch appears to be live and trigger is not os; checking workflow." >> $GITHUB_STEP_SUMMARY
              if curl -sfX GET https://raw.githubusercontent.com/linuxserver/docker-wireguard/${br}/.github/workflows/external_trigger.yml > /dev/null 2>&1; then
                echo "Triggering external trigger workflow for branch." >> $GITHUB_STEP_SUMMARY
                curl -iX POST \
                  -H "Authorization: token ${{ secrets.CR_PAT }}" \
                  -H "Accept: application/vnd.github.v3+json" \
                  -d "{\"ref\":\"refs/heads/${br}\"}" \
                  https://api.github.com/repos/linuxserver/docker-wireguard/actions/workflows/external_trigger.yml/dispatches
              else
                echo "Skipping branch due to no external trigger workflow present." >> $GITHUB_STEP_SUMMARY
              fi
            else
              echo "Skipping branch due to being detected as dev branch or having no external version." >> $GITHUB_STEP_SUMMARY
            fi
          done
